name: Test


on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

env:
  BUILD_TYPE: Release
  GH_USERNAME: github-actions[bot]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Push Linux & macOS binaries
        if: |
          contains(matrix.os, 'latest') &&
          github.event_name == 'push' &&
          github.ref == 'refs/heads/master'
        run: |
          git config --global pull.rebase true
          echo ${{ github.sha }} > ${{ matrix.os }}_commit.txt
          git add ${{ github.workspace }}/${{ matrix.os }}_commit.txt

      - name: Push Linux & macOS binaries
        if: |
          (matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest') &&
          github.event_name == 'push' &&
          github.ref == 'refs/heads/master'
        run: |
          git config --global user.name "${GH_USERNAME}"
          git config --global user.email "${GH_USERNAME}@users.noreply.github.com"
          git diff-index --quiet HEAD || { git commit -m "Add ${{ matrix.os }} binaries" && git pull && git push; }

      # We use cmd /c because powershell <7 does not support chain operators.
      - name: Push Windows binaries
        if: |
          matrix.os == 'windows-latest' &&
          github.event_name == 'push' &&
          github.ref == 'refs/heads/master'
        run: |
          git config --global user.name "${{ env.GH_USERNAME }}"
          git config --global user.email "${{ env.GH_USERNAME }}@users.noreply.github.com"
          cmd /c 'git diff-index --quiet HEAD || ( git commit -m "Add ${{ matrix.os }} binaries" && git pull && git push )'