name: Test

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

env:
  BUILD_TYPE: Release
  GH_USERNAME: ${{ github.actor }}

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.9']

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Debug
        run: |
          echo "github.event.pull_request.merged : $MERGED_RAW"
          echo "contains(matrix.os, 'latest') && contains(matrix.python-version, '3.9') && (github.event.pull_request.merged == true) : $ALLPAR"
          echo "contains(matrix.os, 'latest') && contains(matrix.python-version, '3.9') && github.event.pull_request.merged == true : $ALL"
          echo "github.event.pull_request.merged  == true  : $MERGED_TRUE_BOOL"
          echo "contains(matrix.os, 'latest') && contains(matrix.python-version, '3.9') : $ALL_MAT"
        env:
          MERGED_RAW: ${{ github.event.pull_request.merged }}
          ALLPAR: ${{ contains(matrix.os, 'latest') && contains(matrix.python-version, '3.9') && (github.event.pull_request.merged == true)}}
          ALL: ${{ contains(matrix.os, 'latest') && contains(matrix.python-version, '3.9') && github.event.pull_request.merged == true }}
          MERGED_TRUE_BOOL: ${{ github.event.pull_request.merged == true }}
          ALL_MAT: ${{ contains(matrix.os, 'latest') && contains(matrix.python-version, '3.9') }}

      - name : machine echo $GITHUB_EVENT_NAME
        run : "echo $GITHUB_EVENT_NAME"
      - name : machine echo $GITHUB_BASE_REF
        run : "echo $GITHUB_BASE_REF"
      - name : machine echo $GITHUB_HEAD_REF
        run : "echo $GITHUB_HEAD_REF"
      - name : machine echo $GITHUB_REF
        run : "echo $GITHUB_REF"
      - name : machine echo $GITHUB_SHA
        run : "echo $GITHUB_SHA"
      - name : machine echo $GITHUB_EVENT_PATH
        run : "echo $GITHUB_EVENT_PATH"

      - name: Push binaries
        if: $GITHUB_EVENT_NAME == 'push' && $GITHUB_REF == 'master'
        run: |
          git config --global user.name $GH_USERNAME
          git config --global user.email $GH_USERNAME@users.noreply.github.com
          git config --global pull.rebase false
          git pull
          git add ${{ github.workspace }}/pyfunnel/lib
          git diff-index --quiet HEAD || git commit -m "Add ${{ matrix.os }} binaries"
          git push
